Task 15 - 09/10/2021
On the given dataset perform the following tasks :
1. Clean the data
2. Normalize any required columns
3. Encode the categorical data [ use label encoding only for simplicity ]
4. Divide the data into train test split after separating the features from label
5. Train a decision tree [ Sk Learn ] and calculate its score using score() [ find in decision tree documentation of Sk Learn ]
Note : Take survived column as your target variable.
Deadline for the task is - 11/10/2021 at 23:59

In [1]:

from google.colab import drive
drive.mount('/content/drive')


Mounted at /content/drive


In [46]:
import pandas as pd       # dataframe operations 
import numpy as np        # numeric operations 

In [47]:
path = '/content/drive/MyDrive/Data/data.csv'  # path of the dataset 

df = pd.read_csv(path)  # reads data and stores as dataframe 


In [48]:
df

passenger_id  pclass  ...                 home.dest survived
0            1216       3  ...                       NaN        1
1             699       3  ...                   Croatia        0
2            1267       3  ...                       NaN        0
3             449       2  ...      Cornwall / Akron, OH        1
4             576       2  ...  Barre, Co Washington, VT        0
..            ...     ...  ...                       ...      ...
845           158       1  ...       London / Birmingham        0
846           174       1  ...               Buffalo, NY        0
847           467       2  ...        Moscow / Bronx, NY        1
848          1112       3  ...                       NaN        0
849           425       2  ...                 Bronx, NY        0

[850 rows x 15 columns]

In [49]:
df.shape

(850, 15)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 850 entries, 0 to 849
Data columns (total 15 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   passenger_id  850 non-null    int64  
 1   pclass        850 non-null    int64  
 2   name          850 non-null    object 
 3   sex           850 non-null    object 
 4   age           676 non-null    float64
 5   sibsp         850 non-null    int64  
 6   parch         850 non-null    int64  
 7   ticket        850 non-null    object 
 8   fare          849 non-null    float64
 9   cabin         191 non-null    object 
 10  embarked      849 non-null    object 
 11  boat          308 non-null    object 
 12  body          73 non-null     float64
 13  home.dest     464 non-null    object 
 14  survived      850 non-null    int64  
dtypes: float64(3), int64(5), object(7)
memory usage: 99.7+ KB


In [14]:
# passenger_id, name, ticket, fare can be dropped
df['pclass'].unique() #can be used in model

array([3, 2, 1])

In [10]:
df['sibsp'].unique() #can be used in model

array([0, 1, 2, 8, 5, 4, 3])

In [12]:
df['parch'].unique() #can be used in model

array([0, 1, 3, 2, 9, 4, 6, 5])

In [16]:
df['cabin'].unique() #can be dropped

array([nan, 'C82', 'D15', 'C50', 'E33', 'B57 B59 B63 B66', 'E34', 'C83',
       'C125', 'B82 B84', 'B96 B98', 'B51 B53 B55', 'C132', 'C31', 'C68',
       'B94', 'F E46', 'C126', 'D34', 'B28', 'C65', 'B52 B54 B56', 'D17',
       'C86', 'C7', 'E25', 'E17', 'D56', 'A9', 'B26', 'C91', 'B5', 'D',
       'A23', 'C22 C26', 'C124', 'E63', 'B35', 'B18', 'C6', 'B49', 'B19',
       'G6', 'D35', 'C23 C25 C27', 'C62 C64', 'B73', 'E12', 'B41', 'A20',
       'B69', 'C78', 'A14', 'D26', 'C51', 'B79', 'E52', 'C49', 'C104',
       'B61', 'D43', 'D48', 'C123', 'A7', 'D47', 'D49', 'B80', 'A29',
       'F38', 'B58 B60', 'A34', 'D33', 'D20', 'F G63', 'T', 'A6',
       'C55 C57', 'B38', 'E49', 'F4', 'E121', 'C85', 'C87', 'B86', 'B102',
       'C111', 'D22', 'B22', 'B77', 'B50', 'B30', 'E36', 'F33', 'E60',
       'B39', 'C118', 'D21', 'F2', 'E39 E41', 'E101', 'A32', 'D38',
       'C101', 'C54', 'C106', 'C32', 'D36', 'E50', 'D40', 'C30', 'C52',
       'C130', 'C80', 'F G73', 'E10', 'B10', 'B24', 'C2', 'D28', '

In [18]:
df['embarked'].unique() #can be used in model

array(['Q', 'S', 'C', nan], dtype=object)

In [21]:
df['boat'].unique() #can be dropped as only survived will have boat

array(['13', nan, '4', '10', 'C', '8', '7', '16', '6', 'A', '15', '9',
       '14', '3', '11', '12', '2', '5 7', '5 9', 'B', '5', 'D', '1',
       'C D', '13 15', '13 15 B', '15 16'], dtype=object)

In [22]:
df['body'].unique() #can be dropped

array([ nan, 173., 190.,  38.,  32., 176.,  47.,  45., 110., 328., 196.,
        97.,  69., 312., 147., 135.,   9., 275.,  68.,  14., 305., 181.,
       232., 245., 124., 292., 209., 295., 206., 169., 166.,  37., 260.,
         4., 148., 103., 189., 122., 293.,  58., 286., 261.,  67., 201.,
       121.,  96., 327., 108., 236.,  75., 269.,   7., 234.,  81., 156.,
       155., 119.,  70., 306.,  62.,  89., 149., 208., 309., 307.,  53.,
       197., 283.,  16., 304., 263., 314., 258.,  19.])

In [ ]:
df['home.dest'].unique() #can be dropped

In [50]:
# the columns which provide no info of relevance are dropped from the dataframe 
# axis - 0 : rows , 
df.drop(labels = {'passenger_id', 'name', 'ticket', 'fare', 'cabin' , 'boat', 'body', 'home.dest'} , axis = 1 , inplace = True)
df

pclass     sex   age  sibsp  parch embarked  survived
0         3  female   NaN      0      0        Q         1
1         3    male  38.0      0      0        S         0
2         3  female  30.0      1      1        S         0
3         2  female  54.0      1      3        S         1
4         2    male  40.0      0      0        S         0
..      ...     ...   ...    ...    ...      ...       ...
845       1    male  55.0      0      0        S         0
846       1    male  58.0      0      0        C         0
847       2  female  24.0      1      0        S         1
848       3  female   3.0      1      1        S         0
849       2    male  52.0      0      0        S         0

[850 rows x 7 columns]

In [26]:
df.isnull().sum() # age and embarked have null values

pclass        0
sex           0
age         174
sibsp         0
parch         0
embarked      1
survived      0
dtype: int64

In [51]:
# where age is null, it can be replaced by median
# since only one column no need to used for loop

df['age'].fillna(df['age'].median(), inplace=True)

# replace the embarked value with 'S'

df['embarked'].fillna('S', inplace=True)

In [52]:
df.isnull().sum()

pclass      0
sex         0
age         0
sibsp       0
parch       0
embarked    0
survived    0
dtype: int64

In [53]:
df

pclass     sex   age  sibsp  parch embarked  survived
0         3  female  28.0      0      0        Q         1
1         3    male  38.0      0      0        S         0
2         3  female  30.0      1      1        S         0
3         2  female  54.0      1      3        S         1
4         2    male  40.0      0      0        S         0
..      ...     ...   ...    ...    ...      ...       ...
845       1    male  55.0      0      0        S         0
846       1    male  58.0      0      0        C         0
847       2  female  24.0      1      0        S         1
848       3  female   3.0      1      1        S         0
849       2    male  52.0      0      0        S         0

[850 rows x 7 columns]

In [54]:
# Need encoding for sex and embarked
df['sex'] = np.where(df['sex'] == 'male' , 1 , 0 )

# Label Encoding
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df["embarked"] = le.fit_transform(df["embarked"])

In [55]:
df

pclass  sex   age  sibsp  parch  embarked  survived
0         3    0  28.0      0      0         1         1
1         3    1  38.0      0      0         2         0
2         3    0  30.0      1      1         2         0
3         2    0  54.0      1      3         2         1
4         2    1  40.0      0      0         2         0
..      ...  ...   ...    ...    ...       ...       ...
845       1    1  55.0      0      0         2         0
846       1    1  58.0      0      0         0         0
847       2    0  24.0      1      0         2         1
848       3    0   3.0      1      1         2         0
849       2    1  52.0      0      0         2         0

[850 rows x 7 columns]

In [56]:
# Normalize age

df['age'] = df['age']/df['age'].max()

In [57]:
df

pclass  sex     age  sibsp  parch  embarked  survived
0         3    0  0.3500      0      0         1         1
1         3    1  0.4750      0      0         2         0
2         3    0  0.3750      1      1         2         0
3         2    0  0.6750      1      3         2         1
4         2    1  0.5000      0      0         2         0
..      ...  ...     ...    ...    ...       ...       ...
845       1    1  0.6875      0      0         2         0
846       1    1  0.7250      0      0         0         0
847       2    0  0.3000      1      0         2         1
848       3    0  0.0375      1      1         2         0
849       2    1  0.6500      0      0         2         0

[850 rows x 7 columns]

In [58]:
# separates target variable from the rest of the features 
X = df.drop('survived' , axis = 1) 
Y = df['survived']

In [119]:
from sklearn import model_selection
X_train , X_test , Y_train, Y_test = model_selection.train_test_split(X , Y ,test_size = 0.2, shuffle = True , stratify=Y  )

In [120]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [121]:
from sklearn.tree import DecisionTreeClassifier
clfr = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
clfr.fit(X_train, Y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=0, splitter='best')

In [122]:
Y_pred = clfr.predict(X_test)

In [123]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(Y_test, Y_pred)
print(cm)
accuracy_score(Y_test, Y_pred)

[[97 10]
 [18 45]]


0.8352941176470589